// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAno1_VwV5fD-67nIItEnBAac2KjLdBw',
    appId: '1:289464579611:android:e15df189b5f5bde296eabe',
    messagingSenderId: '289464579611',
    projectId: 'hire-inclusive',
    storageBucket: 'hire-inclusive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRIbjWZeKVe_F7kRc7NWKv9SySZ1BV6s',
    appId: '1:289464579611:ios:3b09f767f7e775b896eabe',
    messagingSenderId: '289464579611',
    projectId: 'hire-inclusive',
    storageBucket: 'hire-inclusive.firebasestorage.app',
    iosBundleId: 'com.example.hireInclusive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRIbjWZeKVe_F7kRc7NWKv9SySZ1BV6s',
    appId: '1:289464579611:ios:3b09f767f7e775b896eabe',
    messagingSenderId: '289464579611',
    projectId: 'hire-inclusive',
    storageBucket: 'hire-inclusive.firebasestorage.app',
    iosBundleId: 'com.example.hireInclusive',
  );
}
